#!bash

rm -rf out && \
mkdir out && \
find -name "*.java" > sources.txt && \
javac -cp libs/* @sources.txt -d out $* && \
rm sources.txt && \
echo -n "" > main && \
k=0 && \
for i in $(find out -name "*.class"); do
  if (
    javap $i |
    grep -F "public static void main(java.lang.String[]);"
  ) > /dev/null; then
    j=${i#*/}
    j=${j%.*}
    j=${j//\//.}
    echo "$j" >> main
    k=$((k + 1))
    l="$j"
  fi
done && \
if [[ $k == 1 ]]; then
  echo $l > main
elif [[ $k == 0 ]]; then
  echo "No main method could be found!" 1>&2
else
  nano main
fi && \
echo "jar{manifest{attributes('Main-Class':$(cat main))}}" && rm main && rm -rf out
