#!bash

rm -rf out && \
mkdir out && \
find -name "*.java" > sources.txt && \
javac -cp libs/* @sources.txt -d out $* && \
rm sources.txt && \
echo -e "# Select Main\n" > manifest.txt && \
k=0 && \
for i in $(find out -name "*.class"); do
  if (
    javap $i |
    grep -F "public static void main(java.lang.String[]);"
  ) > /dev/null; then
    j=${i#*/}
    j=${j%.*}
    j=${j//\//.}
    echo "#Main-Class: $j" >> manifest.txt
    k=$((k + 1))
    l="Main-Class: $j"
  fi
done && \
if [[ $k == 1 ]]; then
  echo $l > manifest.txt
elif [[ $k == 0 ]]; then
  echo "No main method could be found!"
  rm manifest.txt
else
  nano manifest.txt
fi && \
echo "Class-Path: $(find libs -type f)" >> manifest.txt && \
jar cfm out.jar manifest.txt -C out . && \
rm manifest.txt
